import { InjectedFormProps } from 'redux-form';

export const createReduxFormProps = <FormData, Props>(
    overrides?: Partial<InjectedFormProps<FormData, Props>>,
): InjectedFormProps<FormData, Props> => ({
    handleSubmit: jest.fn(handler => handler),
    anyTouched: false,
    array: undefined,
    asyncValidate: jest.fn(),
    asyncValidating: false,
    autofill: jest.fn(),
    blur: jest.fn(),
    change: jest.fn(),
    clearAsyncError: jest.fn(),
    destroy: jest.fn(),
    dirty: false,
    error: '',
    form: '',
    initialize: jest.fn(),
    initialized: true,
    initialValues: undefined,
    invalid: false,
    pristine: true,
    reset: jest.fn(),
    submitFailed: undefined,
    submitSucceeded: undefined,
    submitting: false,
    touch: jest.fn(),
    untouch: jest.fn(),
    valid: false,
    warning: undefined,
    registeredFields: {},
    ...overrides,
});
