//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeStock.Development.Library.Controls {
    
    
    public partial class TextBoc {
        
        /// <summary>
        /// tbx control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HomeStockLibrary.Controls.TextBox tbx;
        
        /// <summary>
        /// Button3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HomeStockLibrary.Controls.Button Button3;
        
        /// <summary>
        /// tbxLbl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HomeStockLibrary.Controls.TextBox tbxLbl;
        
        /// <summary>
        /// tbxLblTag control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HomeStockLibrary.Controls.TextBox tbxLblTag;
        
        /// <summary>
        /// tbxLblTagPH control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HomeStockLibrary.Controls.TextBox tbxLblTagPH;
    }
}
