//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeStock.Development.Library.Data {
    
    
    public partial class Worker {
        
        /// <summary>
        /// HSCore control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HomeStockLibrary.Controls.ClientControls.Workers.Worker HSCore;
        
        /// <summary>
        /// sqlHomeStock control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HomeStockLibrary.Controls.ClientControls.Archives.WebSQL sqlHomeStock;
        
        /// <summary>
        /// homeStockSchema control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HomeStockLibrary.Controls.ClientControls.Schemas.Schema homeStockSchema;
    }
}
