//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeStock {
    
    
    public partial class Site {
        
        /// <summary>
        /// MainViewContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainViewContent;
        
        /// <summary>
        /// SiteMasterScriptAssistant control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HomeStockLibrary.Controls.HomeStockScriptControl SiteMasterScriptAssistant;
        
        /// <summary>
        /// apiHomeStock control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HomeStockLibrary.Data.Suppliers.APISupplier apiHomeStock;
        
        /// <summary>
        /// homeStockSchema control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HomeStockLibrary.Data.Schemas.Schema homeStockSchema;
    }
}
