export const container: string;
export const containerBasic: string;
export const containerError: string;
export const text: string;
export const textBasic: string;
export const textError: string;
export const action: string;
export const actionError: string;
export const actionContainer: string;
